[project]
name = "vsco-downloader"
version = "2.0.1"
description = "A simple python library to extract raw image and video paths from VSCO posts."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.50.0",
    "tls-client>=1.0.1",
]
